### ISSUE TITLE
not sure about my first commit + push procedure

### ISSUE THREAD

**Issue by sabinacuccibar** [WeMakecc/FabAcademy2015-WeMake#1]
@openp2pdesign tried to push everything even if it's still an in progress (I will work on my website tonight for the tomorrow review). I am unsure about the procedure I used (I added every file individually) and most of all I am unsure about have pushed index.html updated file. Please, check here a310193921700fe0aa902f8f8fda73a4acea27ec

**Comment by openp2pdesign** [comment]
You missed index.html... without it, nobody can see the rest of your website! 
Everything else seems good, but I need the index.html in order to browse everything.

**Comment by openp2pdesign** [comment]
I'd remove final_project.html...

**Comment by openp2pdesign** [comment]
And in project01.html, you should transform the links into real <a href="" links

**Comment by openp2pdesign** [comment]
Ok, thanks for the index.html... but please write meaningful (and not repeated) commit messages!

**Comment by sabinacuccibar** [comment]
ok! I will do my best. Thanks massimo! I think this issue can be considered as solved :)
